spring:
  datasource:
    url: jdbc:mysql://geeson.iptime.org:53306/inventory_db
    username: root
    password: rootpass^^*
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092

api:
  version: "2025-06-15"

uuid:
  node-id: ${NODE_ID:0}

server:
  port: 9093