spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092

api:
  version: "2025-06-15"

uuid:
  node-id: ${NODE_ID:0}

server:
  port: 9093
