spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

host:
  order: http://localhost:9093
  payment: http://localhost:9094
  auth: http://localhost:9095

server:
  port: 9090
