spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

host:
  order: http://order-api:8080
  auth: http://auth-api:8080
